---
title: "Regression_tree"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Regression tree after pruning


```{r}

library(readxl)
library(tree)
library(Metrics)


# read file

Store = list()
Store[[1]] = read_excel("Store2-1.xlsx")
Store[[2]] = read_excel("Store3-1.xlsx")
Store[[3]] = read_excel("Store4-1.xlsx")
Store[[4]] = read_excel("Store5-1.xlsx")
Store[[5]] = read_excel("Store6-1.xlsx")
Store[[6]] = read_excel("Store7-1.xlsx")
Store[[7]] = read_excel("Store8-1.xlsx")
Store[[8]] = read_excel("Store9-1.xlsx")

# regression tree
RMSE.prune = list()

for (i in 1:8){
  train = (Store[[i]]$Random == 'Train')
  store_train = Store[[i]][train,][3:98]
  store_test = Store[[i]][!train,][3:98]
  test = Store[[i]][!train,]
  RMSE_prune = c()
  y_test = data.frame(test[99:122])

  for (j in 1:24){
    # regression tree
    f=as.formula(paste(Store[[i]][j+98],"~",paste(colnames(Store[[i]])[3:98],collapse="+")))
    tree.train = tree(f,Store[[i]],subset=train)
    tree.pred=predict(tree.train,store_test)
    plot(tree.train)
    text(tree.train,pretty=0)
    # pruning
    cv.store=cv.tree(tree.train)
    n = cv.store$size[cv.store$dev == min(cv.store$dev)]
    prune.train = prune.tree(tree.train,best=n)
    pred.prune = predict(prune.train,store_test)
    RMSE_prune[j] = rmse(y_test[,j],pred.prune)
  }
  RMSE.prune[[i]] = RMSE_prune
}

name = c('Store_1', 'Store_2',  'Store_3',  'Store_4',  'Store_5', 'Store_6', 'Store_7',  'Store_8')
RMSE.prune = as.data.frame(RMSE.prune)
names(RMSE.prune) = paste(name)
dim(RMSE.prune)
write.csv(RMSE.prune, "prune_new.csv", row.names=FALSE)
```




  
  